"""GPU P1 FEM backend for the TMS E-field (cupy + AMGx)."""

from cunibs.fem.assembly import (
    GM_TAG,
    GRADIENT_TILE_TETS,
    STIFFNESS_TILE_TETS,
    TISSUE_CONDUCTIVITY,
    assemble_stiffness,
    build_node2corner,
    conductivity_per_tet,
    gradient_operator,
)
from cunibs.fem.placement import (
    MU0_OVER_4PI,
    coil_dadt_at_nodes,
    compute_coil_transform,
    compute_coil_transforms,
)
from cunibs.fem.solve import (
    AMGX_CONFIG,
    MAX_BLOCK,
    UQ_AMGX_CONFIG,
    BlockWarmStart,
    GroundedSolver,
    PlacementResult,
    SolverContext,
    build_context,
    ground_node_of,
    grounded_index,
    prepare_grounded_solver,
    reduce_matrix,
    solve_grounded,
    solve_placement,
    solve_placements_block,
)

__all__ = [
    "AMGX_CONFIG",
    "GM_TAG",
    "GRADIENT_TILE_TETS",
    "MAX_BLOCK",
    "MU0_OVER_4PI",
    "STIFFNESS_TILE_TETS",
    "TISSUE_CONDUCTIVITY",
    "UQ_AMGX_CONFIG",
    "BlockWarmStart",
    "GroundedSolver",
    "PlacementResult",
    "SolverContext",
    "assemble_stiffness",
    "build_context",
    "build_node2corner",
    "coil_dadt_at_nodes",
    "compute_coil_transform",
    "compute_coil_transforms",
    "conductivity_per_tet",
    "gradient_operator",
    "ground_node_of",
    "grounded_index",
    "prepare_grounded_solver",
    "reduce_matrix",
    "solve_grounded",
    "solve_placement",
    "solve_placements_block",
]
